### ISSUE TITLE
Shim sometimes using high CPU

### ISSUE THREAD

**Issue by jamiesonbecker** [userify/shim#22]
Reported by two customers; shim is using high CPU:

```
 Traceback (most recent call last):
  File "<stdin>", line 436, in <module>
  File "<stdin>", line 403, in main
  File "<stdin>", line 355, in https
  File "/usr/lib/python2.7/httplib.py", line 958, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 992, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1161, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: _ssl.c:489: The handshake operation timed out 
```

**Comment by jamiesonbecker** [comment]
Having a lot of trouble reproducing this but multiple customers have reported. Please comment if you have more detail!

**Comment by jamiesonbecker** [comment]
We believe this was caused by the DNS migration, because client servers were trying to hit servers that no longer existed. It should be resolved now.
